
version: '3.9'

services:
  youtube-frontend:
    container_name: youtube-frontend
    image: youtube-frontend
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./node_modules:/node_modules/app/
    ports:
      - '8081:80'
    # command: ['node', 'App.js']
  # having command ^ it gave us an exit code 127 removing it and it worked.