
version: '3.9'

services:
  prod-web:
    container_name: youtube-prod
    image: youtube-frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    ports:
      - '8080:80'
    # command: ['node', 'App.js']