version: '3.9'

services:
  web:
    container_name: youtube-clone-dev
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    ports:
      - '3002:3000'

  test:
    container_name: youtube-test
    image: youtube-clone-dev
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    command: ["npm", "run", "test"]