# version: '3.9'

# services:
#   docker-react-aer:
#     container_name: docker-react-aer
#     build:
#       context: ./
#       dockerfile: Dockerfile
#     volumes:
#       - .:/app
#       - '/app/node_modules'
#     ports:
#       - "8080:80"

version: '3.9'

services:
  prod-web:
    container_name: my-awesome-app-bmp-aws
    image: brycepayne/my-awesome-app-bmp:latest
    ports:
      - '80:8080'
    command: ['node', 'app.js']