name: Docker Dev Image CI


on:
  push:
    branches: [devOps]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2

      - name: Runs docker compose
        run: docker-compose -f "docker-compose-dev.yml" up -d --build

  

      